{% set version = "0.1" %}
{% set commit = "088985936518be7e25795a30d8ab33affa9db6ed" %}

{% set apex_proc_type = "cpu" if cuda_compiler_version == "None" else "gpu" %}

package:
  name: nvidia-apex-split
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/apex/archive/{{ commit }}.tar.gz
  sha256: cc5ce27aa30b5ade54d520fafc1cd7d293dfba58c51851759a034d03e3f370bb

build:
  number: 0
  skip: True  # [osx or (not py36) or (win and vc<14)]

outputs:
  - name: nvidia-apex-proc
    version: {{ version }}
    build:
      number: 0
      string: "{{ apex_proc_type }}"
    test:
      commands:
        - exit 0
    about:
      home: https://github.com/conda-forge/nvidia-apex-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU nvidia-apex build.

  - name: nvidia-apex
    version: {{ version }}
    build:
      number: 0
      script: python -m pip install . -vv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
      host:
        - python
        - pytorch
        - setuptools
        - pip
      run:
        - python
        - pytorch
        - cxxfilt  # [linux]
        - tqdm
        - numpy
        - PyYAML
        - pytest
      run_constrained:
        - nvidia-apex-proc * {{ apex_proc_type }}

    test:
      imports:
        - apex
        - apex.amp
        - apex.parallel
        - apex.optimizers
        - apex.normalization.fused_layer_norm

    about:
      home: https://nvidia.github.io/apex/
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: A Pytorch extension with NVIDIA-maintained utilities to streamline mixed precision and distributed training.
      dev_url: https://github.com/NVIDIA/apex

about:
  home: https://nvidia.github.io/apex/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Pytorch extension with NVIDIA-maintained utilities to streamline mixed precision and distributed training.
  dev_url: https://github.com/NVIDIA/apex

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
